import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { recordQueueEntry, saveMyTicket } from '@/lib/antiAbuse';

export interface QueueItem {
  id: string;
  ticket_number: string;
  customer_name: string;
  customer_phone: string;
  service_id: string | null;
  barber_id: string | null;
  status: string;
  priority: string;
  origin: string;
  is_called: boolean;
  called_at: string | null;
  completed_at: string | null;
  created_at: string;
  notes: string | null;
}

export interface Service {
  id: string;
  name: string;
  price: number;
  duration_minutes: number;
  description: string | null;
  is_active: boolean;
}

export interface Barber {
  id: string;
  display_name: string;
  specialty: string | null;
  is_available: boolean;
  is_active: boolean;
  avatar_url: string | null;
}

export interface QueueSettings {
  id: string;
  is_active: boolean;
  opening_time: string;
  closing_time: string;
  max_queue_size: number;
}

// Fetch queue items
export const useQueueItems = (status?: string) => {
  return useQuery({
    queryKey: ['queue-items', status],
    queryFn: async () => {
      let query = supabase
        .from('queue_items')
        .select('*')
        .order('created_at', { ascending: true });
      
      if (status) {
        query = query.eq('status', status);
      }
      
      const { data, error } = await query;
      if (error) throw error;
      return data as QueueItem[];
    },
  });
};

// Fetch today's queue
export const useTodayQueue = () => {
  return useQuery({
    queryKey: ['today-queue'],
    queryFn: async () => {
      const today = new Date().toISOString().split('T')[0];
      const { data, error } = await supabase
        .from('queue_items')
        .select('*')
        .gte('created_at', `${today}T00:00:00`)
        .order('created_at', { ascending: true });
      
      if (error) throw error;
      return data as QueueItem[];
    },
  });
};

// Fetch services
export const useServices = () => {
  return useQuery({
    queryKey: ['services'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('services')
        .select('*')
        .eq('is_active', true)
        .order('name');
      
      if (error) throw error;
      return data as Service[];
    },
  });
};

// Fetch barbers
export const useBarbers = () => {
  return useQuery({
    queryKey: ['barbers'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('barbers')
        .select('*')
        .eq('is_active', true)
        .order('display_name');
      
      if (error) throw error;
      return data as Barber[];
    },
  });
};

// Fetch queue settings
export const useQueueSettings = () => {
  return useQuery({
    queryKey: ['queue-settings'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('queue_settings')
        .select('*')
        .limit(1)
        .single();
      
      if (error && error.code !== 'PGRST116') throw error;
      return data as QueueSettings | null;
    },
  });
};

// Fetch single queue item by ID
export const useQueueItem = (ticketId: string | null) => {
  return useQuery({
    queryKey: ['queue-item', ticketId],
    queryFn: async () => {
      if (!ticketId) return null;
      
      const { data, error } = await supabase
        .from('queue_items')
        .select('*')
        .eq('id', ticketId)
        .single();
      
      if (error) {
        if (error.code === 'PGRST116') return null;
        throw error;
      }
      return data as QueueItem;
    },
    enabled: !!ticketId,
  });
};

// Join queue mutation
export const useJoinQueue = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  
  return useMutation({
    mutationFn: async (data: {
      customer_name: string;
      customer_phone: string;
      service_id?: string;
      barber_id?: string;
      priority?: string;
      origin?: string;
    }) => {
      const { data: result, error } = await supabase
        .from('queue_items')
        .insert([{
          customer_name: data.customer_name,
          customer_phone: data.customer_phone,
          service_id: data.service_id || null,
          barber_id: data.barber_id || null,
          priority: data.priority || 'normal',
          origin: data.origin || 'online',
          status: 'waiting',
          ticket_number: '', // Will be generated by trigger
        }])
        .select()
        .single();
      
      if (error) throw error;
      return result as QueueItem;
    },
    onSuccess: (data) => {
      recordQueueEntry();
      saveMyTicket(data.id);
      queryClient.invalidateQueries({ queryKey: ['queue-items'] });
      queryClient.invalidateQueries({ queryKey: ['today-queue'] });
      toast({
        title: 'Você entrou na fila!',
        description: `Seu ticket é ${data.ticket_number}`,
      });
    },
    onError: (error: Error) => {
      toast({
        title: 'Erro ao entrar na fila',
        description: error.message,
        variant: 'destructive',
      });
    },
  });
};

// Leave queue mutation
export const useLeaveQueue = () => {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  
  return useMutation({
    mutationFn: async (ticketId: string) => {
      const { error } = await supabase
        .from('queue_items')
        .update({ status: 'cancelled', completed_at: new Date().toISOString() })
        .eq('id', ticketId);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['queue-items'] });
      queryClient.invalidateQueries({ queryKey: ['today-queue'] });
      toast({
        title: 'Você saiu da fila',
        description: 'Esperamos vê-lo em breve!',
      });
    },
  });
};
