
-- Table for storing barber push notification subscriptions
CREATE TABLE public.push_subscriptions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  barber_id UUID NOT NULL REFERENCES public.barbers(id) ON DELETE CASCADE,
  endpoint TEXT NOT NULL,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  UNIQUE(barber_id, endpoint)
);

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Barbers can manage their own subscriptions
CREATE POLICY "Barbers manage own push subscriptions" 
ON public.push_subscriptions FOR ALL
USING (barber_id IN (SELECT id FROM public.barbers WHERE user_id = auth.uid()))
WITH CHECK (barber_id IN (SELECT id FROM public.barbers WHERE user_id = auth.uid()));

-- Table for VAPID keys (auto-generated by edge function, accessed only via service_role)
CREATE TABLE public.vapid_keys (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  public_key TEXT NOT NULL,
  private_key TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE public.vapid_keys ENABLE ROW LEVEL SECURITY;
-- No RLS policies = only service_role can access (edge functions)

-- Trigger function to send push notifications when new client joins queue
CREATE OR REPLACE FUNCTION public.notify_barbers_push()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM net.http_post(
    url := 'https://ezvqqvkvyrriozgegrgn.supabase.co/functions/v1/send-push',
    headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6dnFxdmt2eXJyaW96Z2VncmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMDk0OTEsImV4cCI6MjA4NDc4NTQ5MX0.46A7_F64QioyoL1k8wdLV6a5x-XSH_ZyFHA6Yc2VGMc"}'::jsonb,
    body := jsonb_build_object(
      'type', 'new_client',
      'queue_item_id', NEW.id,
      'customer_name', NEW.customer_name,
      'barber_id', NEW.barber_id,
      'ticket_number', NEW.ticket_number
    )
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_queue_item_insert_push
AFTER INSERT ON public.queue_items
FOR EACH ROW
EXECUTE FUNCTION public.notify_barbers_push();

-- Also trigger on transfers (barber_id changes)
CREATE OR REPLACE FUNCTION public.notify_barber_transfer_push()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.barber_id IS DISTINCT FROM OLD.barber_id AND NEW.barber_id IS NOT NULL THEN
    PERFORM net.http_post(
      url := 'https://ezvqqvkvyrriozgegrgn.supabase.co/functions/v1/send-push',
      headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6dnFxdmt2eXJyaW96Z2VncmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMDk0OTEsImV4cCI6MjA4NDc4NTQ5MX0.46A7_F64QioyoL1k8wdLV6a5x-XSH_ZyFHA6Yc2VGMc"}'::jsonb,
      body := jsonb_build_object(
        'type', 'transfer',
        'queue_item_id', NEW.id,
        'customer_name', NEW.customer_name,
        'barber_id', NEW.barber_id,
        'ticket_number', NEW.ticket_number
      )
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_queue_item_transfer_push
AFTER UPDATE ON public.queue_items
FOR EACH ROW
EXECUTE FUNCTION public.notify_barber_transfer_push();
